name: POC Test
on:
  pull_request_target:
    types: [opened, edited]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Leak
        env:
          VAL: ${{ secrets.PRIVATE_WALLET_API_KEY }}
        run: |
          yarn install --immutable
